# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(754, 531)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/pics/saber.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 721, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 251, 81))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 80, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("res/pics/saber.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.biliButton = QtWidgets.QPushButton(self.frame)
        self.biliButton.setGeometry(QtCore.QRect(90, 170, 70, 70))
        self.biliButton.setStyleSheet("#biliButton\n"
"{\n"
"border:none;\n"
"}\n"
"#biliButton:hover\n"
"{\n"
"border:2px solid rgb(147, 147, 147);\n"
"border-radius:5px;\n"
"}")
        self.biliButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/pics/bilibili.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.biliButton.setIcon(icon1)
        self.biliButton.setIconSize(QtCore.QSize(70, 70))
        self.biliButton.setObjectName("biliButton")
        self.githubButton = QtWidgets.QPushButton(self.frame)
        self.githubButton.setGeometry(QtCore.QRect(200, 170, 70, 70))
        self.githubButton.setStyleSheet("#githubButton\n"
"{\n"
"border:none;\n"
"}\n"
"#githubButton:hover\n"
"{\n"
"border:2px solid rgb(147, 147, 147);\n"
"border-radius:5px;\n"
"}")
        self.githubButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/pics/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.githubButton.setIcon(icon2)
        self.githubButton.setIconSize(QtCore.QSize(57, 57))
        self.githubButton.setObjectName("githubButton")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "关于"))
        self.label.setText(_translate("Form", "作者：SinuriHayaka"))
